ad_groups:
  DL_FS_HR_PROJECT_14_RO:
  - hr356
  - mkt78
  - sales444
  - mkt628
  - tech812
  - tech190
  - mkt746
  - sales851
  - sales926
  DL_FS_HR_PROJECT_14_RW:
  - tech815
  - hr20
  - tech298
  - tech496
  - sales787
  - hr720
  - hr779
  - sales639
  - tech576
  DL_FS_HR_PROJECT_18_RO:
  - hr318
  - sales683
  - sales610
  - hr56
  - hr474
  - sales205
  - hr937
  - tech906
  - sales378
  - mkt374
  - hr906
  - tech313
  - sales555
  DL_FS_HR_PROJECT_18_RW:
  - mkt882
  - mkt353
  - mkt234
  - tech627
  - hr589
  - hr880
  - mkt600
  - tech418
  - sales316
  - hr43
  - mkt319
  - sales423
  - mkt966
  DL_FS_HR_PROJECT_68_RO:
  - mkt297
  - tech515
  - hr931
  - tech978
  - mkt16
  - hr504
  - sales197
  - hr42
  - sales667
  - sales23
  DL_FS_HR_PROJECT_68_RW:
  - hr661
  - hr154
  - sales164
  - tech819
  - tech335
  - mkt196
  - mkt53
  - hr689
  - hr753
  - sales123
  DL_FS_HR_PROJECT_71_RO:
  - sales483
  - hr186
  - sales249
  - tech969
  - hr840
  - hr562
  - tech385
  - sales797
  - tech514
  DL_FS_HR_PROJECT_71_RW:
  - sales158
  - sales490
  - tech823
  - tech258
  - hr573
  - hr175
  - hr127
  - sales140
  - sales450
  DL_FS_MKT_PROJECT_29_RO:
  - hr186
  - hr383
  - tech455
  - tech37
  - mkt275
  - sales272
  - hr371
  DL_FS_MKT_PROJECT_29_RW:
  - tech637
  - hr599
  - hr310
  - sales956
  - hr282
  - sales534
  - tech135
  DL_FS_MKT_PROJECT_53_RO:
  - mkt879
  - tech987
  - hr97
  - sales119
  - sales673
  - mkt371
  - mkt683
  - mkt348
  - mkt446
  - hr623
  - mkt355
  - hr385
  - tech412
  - mkt557
  DL_FS_MKT_PROJECT_53_RW:
  - tech844
  - sales426
  - mkt649
  - hr145
  - sales723
  - tech705
  - tech718
  - tech669
  - sales661
  - sales475
  - mkt424
  - mkt374
  - sales49
  - tech57
  DL_FS_MKT_PROJECT_62_RO:
  - hr467
  - tech705
  - tech55
  - sales676
  - mkt678
  - mkt119
  DL_FS_MKT_PROJECT_62_RW:
  - mkt19
  - hr787
  - sales282
  - mkt600
  - hr33
  - hr331
  DL_FS_MKT_PROJECT_67_RO:
  - hr616
  - hr306
  - hr427
  - hr412
  - hr883
  - sales72
  - tech242
  - sales920
  - sales137
  - tech585
  - tech215
  DL_FS_MKT_PROJECT_67_RW:
  - tech902
  - mkt849
  - tech80
  - hr6
  - hr334
  - sales116
  - sales641
  - hr130
  - tech629
  - hr1
  - mkt964
  DL_FS_MKT_PROJECT_77_RO:
  - hr827
  - hr156
  - sales187
  - hr396
  - mkt72
  - hr720
  - sales474
  - mkt192
  - mkt885
  - mkt199
  - hr578
  - tech194
  - tech369
  DL_FS_MKT_PROJECT_77_RW:
  - sales857
  - mkt214
  - sales579
  - hr537
  - hr29
  - tech6
  - hr410
  - tech237
  - mkt336
  - sales888
  - sales534
  - tech314
  - tech768
  DL_FS_MKT_PROJECT_96_RO:
  - mkt252
  - hr26
  - hr614
  - mkt1
  - mkt869
  - sales737
  - tech566
  - sales276
  - mkt983
  - mkt370
  DL_FS_MKT_PROJECT_96_RW:
  - sales934
  - tech890
  - hr883
  - mkt168
  - tech23
  - tech143
  - mkt27
  - mkt644
  - tech634
  - sales529
  DL_FS_MKT_PROJECT_98_RO:
  - hr298
  - mkt379
  - hr396
  - tech745
  - hr929
  - tech207
  - mkt613
  - hr937
  - tech318
  - hr184
  - hr153
  DL_FS_MKT_PROJECT_98_RW:
  - hr593
  - mkt302
  - tech380
  - mkt811
  - sales602
  - sales910
  - sales840
  - hr975
  - mkt927
  - mkt432
  - hr844
  DL_FS_REMOTE_PROJECT_21_RO:
  - remote8
  - remote2
  DL_FS_REMOTE_PROJECT_21_RW:
  - remote18
  - remote17
  - remote14
  - remote13
  - remote1
  - remote12
  - remote11
  - remote3
  - remote6
  - remote10
  - remote15
  - remote7
  DL_FS_REMOTE_PROJECT_35_RO:
  - remote13
  - remote8
  - remote3
  - remote16
  - remote17
  DL_FS_REMOTE_PROJECT_35_RW:
  - remote18
  - remote1
  - remote4
  - remote12
  - remote11
  - remote6
  - remote10
  - remote15
  - remote5
  DL_FS_REMOTE_PROJECT_58_RO:
  - remote1
  - remote8
  - remote3
  - remote10
  - remote15
  - remote5
  - remote7
  DL_FS_REMOTE_PROJECT_58_RW:
  - remote18
  - remote14
  - remote9
  - remote13
  - remote12
  - remote16
  - remote17
  - remote2
  DL_FS_REMOTE_PROJECT_64_RO:
  - remote14
  - remote12
  - remote4
  - remote3
  - remote6
  - remote15
  DL_FS_REMOTE_PROJECT_64_RW:
  - remote18
  - remote1
  - remote8
  - remote16
  - remote10
  - remote2
  - remote7
  DL_FS_REMOTE_PROJECT_7_RO:
  - remote18
  - remote8
  - remote12
  - remote6
  - remote5
  DL_FS_REMOTE_PROJECT_7_RW:
  - remote17
  - remote14
  - remote11
  - remote16
  - remote15
  - remote2
  DL_FS_REMOTE_PROJECT_94_RO:
  - remote10
  - remote8
  - remote3
  DL_FS_REMOTE_PROJECT_94_RW:
  - remote18
  - remote14
  - remote13
  - remote1
  - remote12
  - remote11
  - remote16
  - remote17
  - remote5
  - remote7
  DL_FS_SALES_PROJECT_18_RO:
  - hr9
  - sales675
  - tech51
  - sales28
  - tech522
  - hr21
  DL_FS_SALES_PROJECT_18_RW:
  - sales133
  - tech236
  - mkt88
  - hr741
  - tech66
  - hr44
  DL_FS_SALES_PROJECT_19_RO:
  - hr619
  - sales89
  - tech550
  - sales200
  - hr280
  - hr874
  - tech401
  - tech561
  - hr511
  - hr964
  - hr300
  DL_FS_SALES_PROJECT_19_RW:
  - mkt911
  - tech362
  - mkt707
  - sales189
  - tech400
  - tech415
  - mkt870
  - tech676
  - sales562
  - mkt384
  - tech659
  DL_FS_SALES_PROJECT_1_RO:
  - sales283
  - mkt251
  - tech156
  - hr291
  - sales35
  - mkt314
  - tech619
  - hr850
  - mkt434
  - mkt55
  - sales935
  - tech622
  - mkt868
  - hr699
  - mkt362
  DL_FS_SALES_PROJECT_1_RW:
  - sales112
  - sales62
  - hr476
  - tech200
  - mkt977
  - tech689
  - tech683
  - sales793
  - hr580
  - mkt484
  - tech567
  - tech83
  - hr742
  - mkt390
  - sales272
  DL_FS_SALES_PROJECT_3_RO:
  - hr237
  - tech52
  - mkt210
  - sales933
  - tech469
  DL_FS_SALES_PROJECT_3_RW:
  - mkt882
  - sales116
  - hr638
  - tech656
  - hr630
  DL_FS_SALES_PROJECT_54_RO:
  - mkt44
  - tech857
  - sales961
  - mkt597
  - mkt586
  - hr813
  DL_FS_SALES_PROJECT_54_RW:
  - hr835
  - tech819
  - tech593
  - hr357
  - tech230
  - mkt310
  DL_FS_SALES_PROJECT_74_RO:
  - mkt721
  - tech890
  - tech190
  - hr294
  - tech504
  - tech588
  - hr546
  - sales167
  - hr779
  - hr260
  - sales870
  DL_FS_SALES_PROJECT_74_RW:
  - mkt788
  - mkt40
  - sales487
  - mkt906
  - hr567
  - sales574
  - tech143
  - sales655
  - mkt240
  - hr561
  - mkt978
  DL_FS_TECH_PROJECT_58_RO:
  - mkt40
  - sales19
  - hr177
  - tech761
  - sales20
  - sales905
  - hr937
  - mkt872
  - tech552
  - sales586
  - tech931
  DL_FS_TECH_PROJECT_58_RW:
  - hr22
  - mkt374
  - tech273
  - hr666
  - tech151
  - sales548
  - tech651
  - hr543
  - tech296
  - hr408
  - tech560
  DL_FS_TECH_PROJECT_77_RO:
  - sales64
  - tech517
  - sales416
  - hr722
  - tech17
  - sales255
  - tech802
  - hr272
  - sales808
  - sales644
  - sales881
  - tech936
  - mkt371
  - tech484
  - hr18
  DL_FS_TECH_PROJECT_77_RW:
  - hr88
  - hr659
  - tech438
  - sales239
  - tech172
  - mkt471
  - mkt618
  - sales604
  - sales167
  - hr660
  - hr786
  - mkt472
  - tech424
  - hr152
  - mkt110
file_shares:
  HR_PROJECT_14:
    read: DL_FS_HR_PROJECT_14_RO
    server: CSDRIVE
    write: DL_FS_HR_PROJECT_14_RW
  HR_PROJECT_18:
    read: DL_FS_HR_PROJECT_18_RO
    server: CSDRIVE
    write: DL_FS_HR_PROJECT_18_RW
  HR_PROJECT_68:
    read: DL_FS_HR_PROJECT_68_RO
    server: CSDRIVE
    write: DL_FS_HR_PROJECT_68_RW
  HR_PROJECT_71:
    read: DL_FS_HR_PROJECT_71_RO
    server: CSDRIVE
    write: DL_FS_HR_PROJECT_71_RW
  MKT_PROJECT_29:
    read: DL_FS_MKT_PROJECT_29_RO
    server: CSDRIVE
    write: DL_FS_MKT_PROJECT_29_RW
  MKT_PROJECT_53:
    read: DL_FS_MKT_PROJECT_53_RO
    server: CSDRIVE
    write: DL_FS_MKT_PROJECT_53_RW
  MKT_PROJECT_62:
    read: DL_FS_MKT_PROJECT_62_RO
    server: CSDRIVE
    write: DL_FS_MKT_PROJECT_62_RW
  MKT_PROJECT_67:
    read: DL_FS_MKT_PROJECT_67_RO
    server: CSDRIVE
    write: DL_FS_MKT_PROJECT_67_RW
  MKT_PROJECT_77:
    read: DL_FS_MKT_PROJECT_77_RO
    server: CSDRIVE
    write: DL_FS_MKT_PROJECT_77_RW
  MKT_PROJECT_96:
    read: DL_FS_MKT_PROJECT_96_RO
    server: CSDRIVE
    write: DL_FS_MKT_PROJECT_96_RW
  MKT_PROJECT_98:
    read: DL_FS_MKT_PROJECT_98_RO
    server: CSDRIVE
    write: DL_FS_MKT_PROJECT_98_RW
  REMOTE_PROJECT_21:
    read: DL_FS_REMOTE_PROJECT_21_RO
    server: dc2
    write: DL_FS_REMOTE_PROJECT_21_RW
  REMOTE_PROJECT_35:
    read: DL_FS_REMOTE_PROJECT_35_RO
    server: dc2
    write: DL_FS_REMOTE_PROJECT_35_RW
  REMOTE_PROJECT_58:
    read: DL_FS_REMOTE_PROJECT_58_RO
    server: dc2
    write: DL_FS_REMOTE_PROJECT_58_RW
  REMOTE_PROJECT_64:
    read: DL_FS_REMOTE_PROJECT_64_RO
    server: dc2
    write: DL_FS_REMOTE_PROJECT_64_RW
  REMOTE_PROJECT_7:
    read: DL_FS_REMOTE_PROJECT_7_RO
    server: dc2
    write: DL_FS_REMOTE_PROJECT_7_RW
  REMOTE_PROJECT_94:
    read: DL_FS_REMOTE_PROJECT_94_RO
    server: dc2
    write: DL_FS_REMOTE_PROJECT_94_RW
  SALES_PROJECT_1:
    read: DL_FS_SALES_PROJECT_1_RO
    server: CSDRIVE
    write: DL_FS_SALES_PROJECT_1_RW
  SALES_PROJECT_18:
    read: DL_FS_SALES_PROJECT_18_RO
    server: CSDRIVE
    write: DL_FS_SALES_PROJECT_18_RW
  SALES_PROJECT_19:
    read: DL_FS_SALES_PROJECT_19_RO
    server: CSDRIVE
    write: DL_FS_SALES_PROJECT_19_RW
  SALES_PROJECT_3:
    read: DL_FS_SALES_PROJECT_3_RO
    server: CSDRIVE
    write: DL_FS_SALES_PROJECT_3_RW
  SALES_PROJECT_54:
    read: DL_FS_SALES_PROJECT_54_RO
    server: CSDRIVE
    write: DL_FS_SALES_PROJECT_54_RW
  SALES_PROJECT_74:
    read: DL_FS_SALES_PROJECT_74_RO
    server: CSDRIVE
    write: DL_FS_SALES_PROJECT_74_RW
  TECH_PROJECT_58:
    read: DL_FS_TECH_PROJECT_58_RO
    server: CSDRIVE
    write: DL_FS_TECH_PROJECT_58_RW
  TECH_PROJECT_77:
    read: DL_FS_TECH_PROJECT_77_RO
    server: CSDRIVE
    write: DL_FS_TECH_PROJECT_77_RW
