---
file_shares:
  REMOTE_PROJECT_55:
    read: DL_FS_REMOTE_PROJECT_55_RO
    write: DL_FS_REMOTE_PROJECT_55_RW
  REMOTE_PROJECT_63:
    read: DL_FS_REMOTE_PROJECT_63_RO
    write: DL_FS_REMOTE_PROJECT_63_RW
  REMOTE_PROJECT_74:
    read: DL_FS_REMOTE_PROJECT_74_RO
    write: DL_FS_REMOTE_PROJECT_74_RW
