---
- name: Manage file shares
  hosts: all
  tasks:
    - name: Create AD groups
      microsoft.ad.group:
        identity: '{{ item.key }}'
        scope: domainlocal
        members:
          set: '{{ item.value | list }}'
      loop: '{{ ad_groups | dict2items }}'
      loop_control:
        label: '{{ item.key }}'

    - name: Create file share directory
      ansible.windows.win_file:
        path: C:\project_share
        state: directory

    - name: Create file share directory
      ansible.windows.win_file:
        path: 'C:\project_share\{{ item.key }}'
        state: directory
      loop: '{{ file_shares | dict2items }}'
      loop_control:
        label: '{{ item.key }}'

    - name: Add NTFS permission
      include_tasks: ntfs-permissions.yaml
      loop: '{{ file_shares | dict2items }}'
      loop_control:
        label: '{{ item.key }}'

    - name: Add share
      ansible.windows.win_share:
        name: '{{ item.key }}'
        description: '{{ item.key }} share'
        path: 'C:\project_share\{{ item.key }}'
        full: Everyone
      loop: '{{ file_shares | dict2items }}'
      loop_control:
        label: '{{ item.key }}'