---
- name: Manage file shares
  hosts: fileserver
  tasks:
    - name: Create RO AD groups
      microsoft.ad.group:
        identity: '{{ item.read }}'
        scope: domainlocal
      loop: '{{ file_shares }}'
      loop_control:
        label: '{{ item.name }}'

    - name: Create write AD groups
      microsoft.ad.group:
        identity: '{{ item.write }}'
        scope: domainlocal
      loop: '{{ file_shares }}'
      loop_control:
        label: '{{ item.name }}'

    - name: Create file share directory
      ansible.windows.win_file:
        path: C:\project_share
        state: directory

    - name: Create file share directory
      ansible.windows.win_file:
        path: 'C:\project_share\{{ item.name }}'
        state: directory
      loop: '{{ file_shares }}'
      loop_control:
        label: '{{ item.name }}'

    - name: Add full control permission
      ansible.windows.win_acl:
        user: 'Administrators'
        path: 'C:\project_share\{{ item.name }}'
        type: allow
        rights: FullControl
      loop: '{{ file_shares }}'
      loop_control:
        label: '{{ item.name }}'

    - name: Add write permission
      ansible.windows.win_acl:
        user: '{{ item.write }}'
        path: 'C:\project_share\{{ item.name }}'
        type: allow
        rights: Modify
      loop: '{{ file_shares }}'
      loop_control:
        label: '{{ item.name }}'

    - name: Add read permission
      ansible.windows.win_acl:
        user: '{{ item.read }}'
        path: 'C:\project_share\{{ item.name }}'
        type: allow
        rights: ReadAndExecute
      loop: '{{ file_shares }}'
      loop_control:
        label: '{{ item.name }}'

    - name: Disable inheritance
      ansible.windows.win_acl_inheritance:
        path: 'C:\project_share\{{ item.name }}'
        state: absent
      loop: '{{ file_shares }}'
      loop_control:
        label: '{{ item.name }}'

    - name: Add share
      ansible.windows.win_share:
        name: '{{ item.name }}'
        description: '{{ item.name }} share'
        path: 'C:\project_share\{{ item.name }}'
        full: Everyone
      loop: '{{ file_shares }}'
      loop_control:
        label: '{{ item.name }}'